# This file was generated by GoReleaser. DO NOT EDIT.
cask "kzero" do
  version "0.7.4"

  on_macos do
    on_intel do
      sha256 "a3b7b552a0c459277e9a3be02c2350c32149d7e0177536c49cc82b55d4371bd6"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
    on_arm do
      sha256 "e85e12396772ecd8643984c9b1f5fa3ea12b74178b22ff0fd9586a0e8f5ba760"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
  end

  on_linux do
    on_intel do
      sha256 "beed1fb439363e31f86444b3d498f799875f1f39a39e1ca3e03163c9e418fed3"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
    on_arm do
      sha256 "18ff1bf91fc89997e66debf61aa1f4a87fd2fbb44dd0df57d8200afe14ddae66"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
  end

  name "kzero"
  desc "Declarative Kubernetes workload down/up/reset pipelines from YAML"
  homepage "https://github.com/hrodrig/kzero"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kzero"
  manpage "share/man/man1/kzero.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kzero"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Sample configuration is not bundled with the Homebrew cask.
    Generate it with `kzero --print-sample-config > kzero.yaml`.
  EOS
end
