# This file was generated by GoReleaser. DO NOT EDIT.
cask "kzero" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "dce38529e1ac9e5fb323d3314ed408305de20286cac4eceb9fdfe4d4d4d37b21"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
    on_arm do
      sha256 "165d25ec02c5b3bab1b66e74cce6810c88eb7a835253bf1e2a33ef8bbb9c8b20"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c992b340a4f4faff5e337c2925fb8460f4ebde96ad1eac71664486506dd8e47"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
    on_arm do
      sha256 "f759a7585d43f89eae6420194a4855598dd08efd85d2bc538834d5524c57b288"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
  end

  name "kzero"
  desc "Declarative Kubernetes workload down/up/reset pipelines from YAML"
  homepage "https://github.com/hrodrig/kzero"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kzero"
  manpage "share/man/man1/kzero.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kzero"]
    end
  end

  # No zap stanza required

end
