# This file was generated by GoReleaser. DO NOT EDIT.
cask "kzero" do
  version "0.7.3"

  on_macos do
    on_intel do
      sha256 "2d9cc7bd8b713d2ec7c3471f4c1a337012e5af0f21a78298afd8f6870b00d85e"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
    on_arm do
      sha256 "0d536d0668a8982386bf72e37a174ffde0c005ec6f9c9323ddf7b3f772258828"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
  end

  on_linux do
    on_intel do
      sha256 "9d912d803da90e30b80b9e1c0486889545c956c52681405aed31ef12b3ef692b"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
    on_arm do
      sha256 "49d28a3f1126ae6c449a567faff3e96e1990cc4b1e7c61e2754d6414fcfa957c"
      url "https://github.com/hrodrig/kzero/releases/download/v#{version}/kzero_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/kzero/"
    end
  end

  name "kzero"
  desc "Declarative Kubernetes workload down/up/reset pipelines from YAML"
  homepage "https://github.com/hrodrig/kzero"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kzero"
  manpage "share/man/man1/kzero.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kzero"]
    end
  end

  # No zap stanza required

end
